/* tslint:disable */
/* eslint-disable */
/**
 * QuestBook Data Validator
 * Validates data, uploads & pins it to IPFS
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ApplicationMilestoneUpdate
 */
export interface ApplicationMilestoneUpdate {
    /**
     * 
     * @type {string}
     * @memberof ApplicationMilestoneUpdate
     */
    'text': string;
}
/**
 * 
 * @export
 * @interface GrantApplicationFieldAnswerItem
 */
export interface GrantApplicationFieldAnswerItem {
    /**
     * 
     * @type {string}
     * @memberof GrantApplicationFieldAnswerItem
     */
    'value': string;
}
/**
 * 
 * @export
 * @interface GrantApplicationRequest
 */
export interface GrantApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof GrantApplicationRequest
     */
    'grantId': string;
    /**
     * 
     * @type {string}
     * @memberof GrantApplicationRequest
     */
    'applicantId': string;
    /**
     * Maps ID of the field to the answer by the applicant
     * @type {{ [key: string]: Array<GrantApplicationFieldAnswerItem>; }}
     * @memberof GrantApplicationRequest
     */
    'fields': { [key: string]: Array<GrantApplicationFieldAnswerItem>; };
    /**
     * Map of encrypted information mapped by the wallet ID, whose public key was used to map the specific information
     * @type {{ [key: string]: string; }}
     * @memberof GrantApplicationRequest
     */
    'pii'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<GrantProposedMilestone>}
     * @memberof GrantApplicationRequest
     */
    'milestones': Array<GrantProposedMilestone>;
}
/**
 * 
 * @export
 * @interface GrantApplicationUpdate
 */
export interface GrantApplicationUpdate {
    /**
     * Maps ID of the field to the answer by the applicant
     * @type {{ [key: string]: Array<GrantApplicationFieldAnswerItem>; }}
     * @memberof GrantApplicationUpdate
     */
    'fields'?: { [key: string]: Array<GrantApplicationFieldAnswerItem>; };
    /**
     * Map of encrypted information mapped by the wallet ID, whose public key was used to map the specific information
     * @type {{ [key: string]: string; }}
     * @memberof GrantApplicationUpdate
     */
    'pii'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<GrantProposedMilestone>}
     * @memberof GrantApplicationUpdate
     */
    'milestones'?: Array<GrantProposedMilestone>;
    /**
     * 
     * @type {string}
     * @memberof GrantApplicationUpdate
     */
    'feedback'?: string;
}
/**
 * 
 * @export
 * @interface GrantCreateRequest
 */
export interface GrantCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof GrantCreateRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof GrantCreateRequest
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof GrantCreateRequest
     */
    'details': string;
    /**
     * Deadline of the application
     * @type {string}
     * @memberof GrantCreateRequest
     */
    'deadline'?: string;
    /**
     * 
     * @type {GrantReward}
     * @memberof GrantCreateRequest
     */
    'reward': GrantReward;
    /**
     * 
     * @type {string}
     * @memberof GrantCreateRequest
     */
    'creatorId': string;
    /**
     * the workspace the grant is from
     * @type {string}
     * @memberof GrantCreateRequest
     */
    'workspaceId': string;
    /**
     * 
     * @type {GrantFieldMap}
     * @memberof GrantCreateRequest
     */
    'fields': GrantFieldMap;
    /**
     * 
     * @type {Array<string>}
     * @memberof GrantCreateRequest
     */
    'grantManagers'?: Array<string>;
    /**
     * Map of evaluation rubric ID to rubric data
     * @type {{ [key: string]: RubricItem; }}
     * @memberof GrantCreateRequest
     */
    'rubric'?: { [key: string]: RubricItem; };
}
/**
 * 
 * @export
 * @interface GrantField
 */
export interface GrantField {
    /**
     * Human readable title of the field
     * @type {string}
     * @memberof GrantField
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof GrantField
     */
    'inputType': GrantFieldInputTypeEnum;
    /**
     * Constraint possible inputs for this field
     * @type {Array<string>}
     * @memberof GrantField
     */
    'enum'?: Array<string>;
    /**
     * Whether this field is PII (personally identifiable information) or not
     * @type {boolean}
     * @memberof GrantField
     */
    'pii'?: boolean;
}

export const GrantFieldInputTypeEnum = {
    ShortForm: 'short-form',
    LongForm: 'long-form',
    Numeric: 'numeric',
    Array: 'array'
} as const;

export type GrantFieldInputTypeEnum = typeof GrantFieldInputTypeEnum[keyof typeof GrantFieldInputTypeEnum];

/**
 * 
 * @export
 * @interface GrantFieldMap
 */
export interface GrantFieldMap {
    [key: string]: GrantField | any;

    /**
     * 
     * @type {GrantField}
     * @memberof GrantFieldMap
     */
    'applicantName': GrantField;
    /**
     * 
     * @type {GrantField}
     * @memberof GrantFieldMap
     */
    'applicantEmail': GrantField;
    /**
     * 
     * @type {GrantField}
     * @memberof GrantFieldMap
     */
    'projectName': GrantField;
    /**
     * 
     * @type {GrantField}
     * @memberof GrantFieldMap
     */
    'projectDetails': GrantField;
    /**
     * 
     * @type {GrantField}
     * @memberof GrantFieldMap
     */
    'fundingBreakdown': GrantField;
}
/**
 * 
 * @export
 * @interface GrantProposedMilestone
 */
export interface GrantProposedMilestone {
    /**
     * 
     * @type {string}
     * @memberof GrantProposedMilestone
     */
    'title': string;
    /**
     * Positive integer amount of currency. Is a string to allow bigint inputs
     * @type {number}
     * @memberof GrantProposedMilestone
     */
    'amount': string;
}
/**
 * 
 * @export
 * @interface GrantReward
 */
export interface GrantReward {
    /**
     * Positive integer amount of currency. Is a string to allow bigint inputs
     * @type {number}
     * @memberof GrantReward
     */
    'committed': string;
    /**
     * 
     * @type {string}
     * @memberof GrantReward
     */
    'asset': string;
}
/**
 * 
 * @export
 * @interface GrantUpdateRequest
 */
export interface GrantUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof GrantUpdateRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof GrantUpdateRequest
     */
    'summary'?: string;
    /**
     * 
     * @type {string}
     * @memberof GrantUpdateRequest
     */
    'details'?: string;
    /**
     * Deadline of the application
     * @type {string}
     * @memberof GrantUpdateRequest
     */
    'deadline'?: string;
    /**
     * 
     * @type {GrantReward}
     * @memberof GrantUpdateRequest
     */
    'reward'?: GrantReward;
    /**
     * 
     * @type {GrantFieldMap}
     * @memberof GrantUpdateRequest
     */
    'fields'?: GrantFieldMap;
    /**
     * 
     * @type {Array<string>}
     * @memberof GrantUpdateRequest
     */
    'grantManagers'?: Array<string>;
    /**
     * Map of evaluation rubric ID to rubric data
     * @type {{ [key: string]: RubricItem; }}
     * @memberof GrantUpdateRequest
     */
    'rubric'?: { [key: string]: RubricItem; };
}
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * IPFS hash of the uploaded grant
     * @type {string}
     * @memberof InlineResponse200
     */
    'ipfsHash': string;
    /**
     * http url that can be used to fetch the uploaded grant file
     * @type {string}
     * @memberof InlineResponse200
     */
    'url': string;
}
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {number}
     * @memberof ModelError
     */
    'statusCode': number;
    /**
     * Specific description of the error
     * @type {string}
     * @memberof ModelError
     */
    'error': string;
    /**
     * What the error was
     * @type {string}
     * @memberof ModelError
     */
    'message': string;
    /**
     * Some extra information about the error
     * @type {object}
     * @memberof ModelError
     */
    'data'?: object;
}
/**
 * 
 * @export
 * @interface ReviewItem
 */
export interface ReviewItem {
    /**
     * 
     * @type {number}
     * @memberof ReviewItem
     */
    'rating': number;
    /**
     * Content or IPFS hash of the review note
     * @type {string}
     * @memberof ReviewItem
     */
    'note'?: string;
}
/**
 * 
 * @export
 * @interface ReviewSetRequest
 */
export interface ReviewSetRequest {
    /**
     * 
     * @type {string}
     * @memberof ReviewSetRequest
     */
    'reviewer': string;
    /**
     * Encrypted review data. Map of the grant manager address => IPFS hash of the review encrypted with their public key
     * @type {{ [key: string]: string; }}
     * @memberof ReviewSetRequest
     */
    'encryptedReview': { [key: string]: string; };
}
/**
 * 
 * @export
 * @interface RubricItem
 */
export interface RubricItem {
    /**
     * 
     * @type {string}
     * @memberof RubricItem
     */
    'title': string;
    /**
     * Details about the evaluatation rubric
     * @type {string}
     * @memberof RubricItem
     */
    'details'?: string;
}
/**
 * 
 * @export
 * @interface SocialItem
 */
export interface SocialItem {
    /**
     * 
     * @type {string}
     * @memberof SocialItem
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof SocialItem
     */
    'value': string;
}
/**
 * Chain ID of the network
 * @export
 * @enum {string}
 */

export const SupportedNetwork = {
    _1: '1',
    _4: '4',
    _137: '137',
    _80001: '80001',
    _1666700000: '1666700000',
    _1666600000: '1666600000'
} as const;

export type SupportedNetwork = typeof SupportedNetwork[keyof typeof SupportedNetwork];


/**
 * 
 * @export
 * @interface WorkspaceCreateRequest
 */
export interface WorkspaceCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreateRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreateRequest
     */
    'about': string;
    /**
     * IPFS hash of the logo of the workspace
     * @type {string}
     * @memberof WorkspaceCreateRequest
     */
    'logoIpfsHash': string;
    /**
     * IPFS hash of the cover of the workspace
     * @type {string}
     * @memberof WorkspaceCreateRequest
     */
    'coverImageIpfsHash'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreateRequest
     */
    'creatorId': string;
    /**
     * The public encryption key associated with the account address
     * @type {string}
     * @memberof WorkspaceCreateRequest
     */
    'creatorPublicKey'?: string;
    /**
     * 
     * @type {Array<SupportedNetwork>}
     * @memberof WorkspaceCreateRequest
     */
    'supportedNetworks': Array<SupportedNetwork>;
    /**
     * 
     * @type {Array<SocialItem>}
     * @memberof WorkspaceCreateRequest
     */
    'socials': Array<SocialItem>;
}
/**
 * 
 * @export
 * @interface WorkspaceUpdateRequest
 */
export interface WorkspaceUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceUpdateRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceUpdateRequest
     */
    'about'?: string;
    /**
     * IPFS hash of the logo of the workspace
     * @type {string}
     * @memberof WorkspaceUpdateRequest
     */
    'logoIpfsHash'?: string;
    /**
     * IPFS hash of the cover of the workspace
     * @type {string}
     * @memberof WorkspaceUpdateRequest
     */
    'coverImageIpfsHash'?: string;
    /**
     * 
     * @type {Array<SocialItem>}
     * @memberof WorkspaceUpdateRequest
     */
    'socials'?: Array<SocialItem>;
    /**
     * The public encryption key associated with the account address
     * @type {string}
     * @memberof WorkspaceUpdateRequest
     */
    'publicKey'?: string;
}

/**
 * ValidationApi - axios parameter creator
 * @export
 */
export const ValidationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Validate, upload & pin grant application milestone to IPFS
         * @param {ApplicationMilestoneUpdate} [applicationMilestoneUpdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateApplicationMilestoneUpdate: async (applicationMilestoneUpdate?: ApplicationMilestoneUpdate, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/validate/application-milestone-update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(applicationMilestoneUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Validate, upload & pin grant application data to IPFS
         * @param {GrantApplicationRequest} [grantApplicationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateGrantApplicationCreate: async (grantApplicationRequest?: GrantApplicationRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/validate/grant-application-create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(grantApplicationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Validate, upload & pin grant application data to IPFS
         * @param {GrantApplicationUpdate} [grantApplicationUpdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateGrantApplicationUpdate: async (grantApplicationUpdate?: GrantApplicationUpdate, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/validate/grant-application-update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(grantApplicationUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Validate, upload & pin grant to IPFS
         * @param {GrantCreateRequest} [grantCreateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateGrantCreate: async (grantCreateRequest?: GrantCreateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/validate/grant-create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(grantCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Validate & update grant to IPFS
         * @param {GrantUpdateRequest} [grantUpdateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateGrantUpdate: async (grantUpdateRequest?: GrantUpdateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/validate/grant-update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(grantUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Set the review for an application
         * @param {ReviewSetRequest} [reviewSetRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateReviewSet: async (reviewSetRequest?: ReviewSetRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/validate/review-set`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reviewSetRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Validate, upload & pin workspace data to IPFS
         * @param {WorkspaceCreateRequest} [workspaceCreateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateWorkspaceCreate: async (workspaceCreateRequest?: WorkspaceCreateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/validate/workspace-create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(workspaceCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Validate, upload & pin workspace patch data to IPFS
         * @param {WorkspaceUpdateRequest} [workspaceUpdateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateWorkspaceUpdate: async (workspaceUpdateRequest?: WorkspaceUpdateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/validate/workspace-update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(workspaceUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ValidationApi - functional programming interface
 * @export
 */
export const ValidationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ValidationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Validate, upload & pin grant application milestone to IPFS
         * @param {ApplicationMilestoneUpdate} [applicationMilestoneUpdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateApplicationMilestoneUpdate(applicationMilestoneUpdate?: ApplicationMilestoneUpdate, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateApplicationMilestoneUpdate(applicationMilestoneUpdate, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Validate, upload & pin grant application data to IPFS
         * @param {GrantApplicationRequest} [grantApplicationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateGrantApplicationCreate(grantApplicationRequest?: GrantApplicationRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateGrantApplicationCreate(grantApplicationRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Validate, upload & pin grant application data to IPFS
         * @param {GrantApplicationUpdate} [grantApplicationUpdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateGrantApplicationUpdate(grantApplicationUpdate?: GrantApplicationUpdate, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateGrantApplicationUpdate(grantApplicationUpdate, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Validate, upload & pin grant to IPFS
         * @param {GrantCreateRequest} [grantCreateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateGrantCreate(grantCreateRequest?: GrantCreateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateGrantCreate(grantCreateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Validate & update grant to IPFS
         * @param {GrantUpdateRequest} [grantUpdateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateGrantUpdate(grantUpdateRequest?: GrantUpdateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateGrantUpdate(grantUpdateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Set the review for an application
         * @param {ReviewSetRequest} [reviewSetRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateReviewSet(reviewSetRequest?: ReviewSetRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateReviewSet(reviewSetRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Validate, upload & pin workspace data to IPFS
         * @param {WorkspaceCreateRequest} [workspaceCreateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateWorkspaceCreate(workspaceCreateRequest?: WorkspaceCreateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateWorkspaceCreate(workspaceCreateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Validate, upload & pin workspace patch data to IPFS
         * @param {WorkspaceUpdateRequest} [workspaceUpdateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateWorkspaceUpdate(workspaceUpdateRequest?: WorkspaceUpdateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateWorkspaceUpdate(workspaceUpdateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ValidationApi - factory interface
 * @export
 */
export const ValidationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ValidationApiFp(configuration)
    return {
        /**
         * 
         * @summary Validate, upload & pin grant application milestone to IPFS
         * @param {ApplicationMilestoneUpdate} [applicationMilestoneUpdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateApplicationMilestoneUpdate(applicationMilestoneUpdate?: ApplicationMilestoneUpdate, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.validateApplicationMilestoneUpdate(applicationMilestoneUpdate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Validate, upload & pin grant application data to IPFS
         * @param {GrantApplicationRequest} [grantApplicationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateGrantApplicationCreate(grantApplicationRequest?: GrantApplicationRequest, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.validateGrantApplicationCreate(grantApplicationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Validate, upload & pin grant application data to IPFS
         * @param {GrantApplicationUpdate} [grantApplicationUpdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateGrantApplicationUpdate(grantApplicationUpdate?: GrantApplicationUpdate, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.validateGrantApplicationUpdate(grantApplicationUpdate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Validate, upload & pin grant to IPFS
         * @param {GrantCreateRequest} [grantCreateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateGrantCreate(grantCreateRequest?: GrantCreateRequest, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.validateGrantCreate(grantCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Validate & update grant to IPFS
         * @param {GrantUpdateRequest} [grantUpdateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateGrantUpdate(grantUpdateRequest?: GrantUpdateRequest, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.validateGrantUpdate(grantUpdateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Set the review for an application
         * @param {ReviewSetRequest} [reviewSetRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateReviewSet(reviewSetRequest?: ReviewSetRequest, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.validateReviewSet(reviewSetRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Validate, upload & pin workspace data to IPFS
         * @param {WorkspaceCreateRequest} [workspaceCreateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateWorkspaceCreate(workspaceCreateRequest?: WorkspaceCreateRequest, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.validateWorkspaceCreate(workspaceCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Validate, upload & pin workspace patch data to IPFS
         * @param {WorkspaceUpdateRequest} [workspaceUpdateRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateWorkspaceUpdate(workspaceUpdateRequest?: WorkspaceUpdateRequest, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.validateWorkspaceUpdate(workspaceUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ValidationApi - object-oriented interface
 * @export
 * @class ValidationApi
 * @extends {BaseAPI}
 */
export class ValidationApi extends BaseAPI {
    /**
     * 
     * @summary Validate, upload & pin grant application milestone to IPFS
     * @param {ApplicationMilestoneUpdate} [applicationMilestoneUpdate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApi
     */
    public validateApplicationMilestoneUpdate(applicationMilestoneUpdate?: ApplicationMilestoneUpdate, options?: AxiosRequestConfig) {
        return ValidationApiFp(this.configuration).validateApplicationMilestoneUpdate(applicationMilestoneUpdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Validate, upload & pin grant application data to IPFS
     * @param {GrantApplicationRequest} [grantApplicationRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApi
     */
    public validateGrantApplicationCreate(grantApplicationRequest?: GrantApplicationRequest, options?: AxiosRequestConfig) {
        return ValidationApiFp(this.configuration).validateGrantApplicationCreate(grantApplicationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Validate, upload & pin grant application data to IPFS
     * @param {GrantApplicationUpdate} [grantApplicationUpdate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApi
     */
    public validateGrantApplicationUpdate(grantApplicationUpdate?: GrantApplicationUpdate, options?: AxiosRequestConfig) {
        return ValidationApiFp(this.configuration).validateGrantApplicationUpdate(grantApplicationUpdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Validate, upload & pin grant to IPFS
     * @param {GrantCreateRequest} [grantCreateRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApi
     */
    public validateGrantCreate(grantCreateRequest?: GrantCreateRequest, options?: AxiosRequestConfig) {
        return ValidationApiFp(this.configuration).validateGrantCreate(grantCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Validate & update grant to IPFS
     * @param {GrantUpdateRequest} [grantUpdateRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApi
     */
    public validateGrantUpdate(grantUpdateRequest?: GrantUpdateRequest, options?: AxiosRequestConfig) {
        return ValidationApiFp(this.configuration).validateGrantUpdate(grantUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Set the review for an application
     * @param {ReviewSetRequest} [reviewSetRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApi
     */
    public validateReviewSet(reviewSetRequest?: ReviewSetRequest, options?: AxiosRequestConfig) {
        return ValidationApiFp(this.configuration).validateReviewSet(reviewSetRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Validate, upload & pin workspace data to IPFS
     * @param {WorkspaceCreateRequest} [workspaceCreateRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApi
     */
    public validateWorkspaceCreate(workspaceCreateRequest?: WorkspaceCreateRequest, options?: AxiosRequestConfig) {
        return ValidationApiFp(this.configuration).validateWorkspaceCreate(workspaceCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Validate, upload & pin workspace patch data to IPFS
     * @param {WorkspaceUpdateRequest} [workspaceUpdateRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ValidationApi
     */
    public validateWorkspaceUpdate(workspaceUpdateRequest?: WorkspaceUpdateRequest, options?: AxiosRequestConfig) {
        return ValidationApiFp(this.configuration).validateWorkspaceUpdate(workspaceUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


